import {RemoveTestDb} from './setup';
import './authenv';
import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {GetDb} from '../src/db';
import {users,userapikeys} from '../src/db/schema';
import {HashUserAPIKey,SignMetagameJWTForUid,ValidateMetagameJWTAndGetPayload} from '../src/controllers/auth';
import {BanFor,CheckPlayerAccess,ModerationInfo,SetAccountBan} from '../src/controllers/moderation';
import {app} from '../src/app';
after(()=>RemoveTestDb(()=>GetDb().$client.close()));
test('trusted IP logging, account/IP bans, required reasons, JWT revocation and unban',async()=>{
  const db=GetDb();
  db.insert(users).values([{userId:'UID-ban-test',name:'BanTest',notes:0},{userId:'UID-admin-test',name:'AdminTest',notes:0,isAdmin:true}]).run();
  const key='UUK_'+ 'a'.repeat(48),admin='UUK_'+'b'.repeat(48);
  db.insert(userapikeys).values([{userId:'UID-ban-test',keyHash:HashUserAPIKey(key)},{userId:'UID-admin-test',keyHash:HashUserAPIKey(admin)}]).run();
  const token=SignMetagameJWTForUid('UID-ban-test');
  process.env.GATEWAY_SECRET='test-gateway-secret';
  const req:any={socket:{remoteAddress:'127.0.0.1'},headers:{'x-forwarded-for':'203.0.113.9'}};
  const response:any={status(){return this},json(){return this}};
  CheckPlayerAccess(req,response,'UID-ban-test');
  assert.equal(ModerationInfo('UID-ban-test').addresses.length,0);
  req.headers['x-dauntless-gateway']='test-gateway-secret';
  CheckPlayerAccess(req,response,'UID-ban-test');
  assert.equal(ModerationInfo('UID-ban-test').addresses.length,1);
  assert.throws(()=>SetAccountBan('UID-ban-test',' ',true,null,'owner'),/invalid_ban/);
  assert.throws(()=>SetAccountBan('UID-admin-test','reason',true,null,'owner'),/protected/);
  assert.throws(()=>SetAccountBan('UID-ban-test','reason',true,'203.0.113.10','owner'),/not_observed/);
  SetAccountBan('UID-ban-test','Repeated harassment',true,'203.0.113.9','owner');
  assert.equal(BanFor('UID-other','203.0.113.9')?.reason,'Repeated harassment');
  assert.throws(()=>ValidateMetagameJWTAndGetPayload(token),/account_banned/);
  const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));
  const port=(server.address() as any).port;
  try {
    const request=async(path:string,k:string,body?:unknown)=>fetch(`http://127.0.0.1:${port}${path}`,{method:body?'POST':'GET',headers:{'x-undaunted-user-api-key':k,'content-type':'application/json'},body:body?JSON.stringify(body):undefined});
    const reply=await request('/undaunted/api/GetUserInfo',key);assert.equal(reply.status,403);assert.deepEqual(await reply.json(),{error:'account_banned',reason:'Repeated harassment'});
    assert.equal((await request('/undaunted/api/Moderation/UID-ban-test',key)).status,403);
    assert.equal((await request('/undaunted/api/Moderation',admin,{accountId:'UID-ban-test',reason:'Appeal accepted',active:false})).status,200);
    assert.equal((await request('/undaunted/api/GetUserInfo',key)).status,200);
    assert.equal(BanFor('UID-other','203.0.113.9'),undefined);
    assert.ok(ValidateMetagameJWTAndGetPayload(token));
  }finally{await new Promise<void>((r,j)=>server.close(e=>e?j(e):r()));delete process.env.GATEWAY_SECRET;}
});
